# Generated by Django 4.2.21 on 2025-12-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_category_tag_post_category_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(blank=True, to="posts.category"),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="published",
                max_length=10,
            ),
        ),
    ]
