# Generated by Django 4.2.21 on 2025-12-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_category_post_categories_post_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="read_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, unique_for_date="created_at"
            ),
        ),
    ]
