# Generated by Django 4.2.21 on 2025-12-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_read_time_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
