# Generated by Django 4.2.21 on 2025-12-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="github_handle",
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="twitter_handle",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
